export const imgProfileSquare = "/imgProfileSquare.webp";
export const imgProfileSquareSmall = "/imgProfileSquare-small.webp";
export const profileImg = "/profileImg.webp";
export const profileImgSmall = "/profileImg-small.webp";

export const skillsLogos: Record<SkillName, string> = {
  reactJs: "/skills/reactJs.webp",
  nodeJs: "/skills/nodeJs.webp",
  typeScript: "/skills/typescript.webp",
  javaScript: "/skills/javaScript.webp",
  meteor: "/skills/meteorJs.webp",
  flutter: "/skills/flutter.webp",
  bootstrap: "/skills/bootstrap.webp",
  materialUI: "/skills/materialUI.webp",
  tailwindCss: "/skills/tailwind.webp",
  primeFaces: "/skills/primereact.webp",
  sass: "/skills/sass.webp",
  mongoDB: "/skills/mongodb.webp",
  monorepo: "/skills/monorepo.webp",
  turborepo: "/skills/turborepo.webp",
  net: "/skills/dotnet.webp",
  sql: "/skills/sql.webp",
  rxJs: "/skills/rxJs.webp",
  git: "/skills/git.webp",
  jira: "/skills/jira.webp",
  redux: "/skills/redux.webp",
  nextJs: "/skills/nextJs.webp",
  storybook: "/skills/storybook.webp",
  svelte: "/skills/svelte.webp",
  angular: "/skills/angular.webp",
  agile: "/skills/agile.webp",
  github: "/skills/github.webp",
  nestJs: "/skills/nestJs.webp",
  html: "/skills/html.webp",
  css: "/skills/css.webp",
  framerMotion: "/skills/framerMotion.webp",
};

export const projectImages: Record<
  ProjectNames,
  {
    original: string[];
    small: string[];
    main: string;
    mainSmall: string;
    collage: string;
    collageSmall: string;
    logo: string;
  }
> = {
  apia: {
    main: "/projects/apia/main.webp",
    mainSmall: "/projects/apia/main-small.webp",
    collage: "/projects/apia/collage.webp",
    collageSmall: "/projects/apia/collage-small.webp",
    logo: "/projects/apia/logo.webp",
    original: [
      "/projects/apia/apia1.webp",
      "/projects/apia/apia2.webp",
      "/projects/apia/apia3.webp",
      "/projects/apia/apia4.webp",
      "/projects/apia/apia5.webp",
      "/projects/apia/apia6.webp",
      "/projects/apia/apia7.webp",
      "/projects/apia/apia8.webp",
      "/projects/apia/apia9.webp",
    ],
    small: [
      "/projects/apia/apia1-small.webp",
      "/projects/apia/apia2-small.webp",
      "/projects/apia/apia3-small.webp",
      "/projects/apia/apia4-small.webp",
      "/projects/apia/apia5-small.webp",
      "/projects/apia/apia6-small.webp",
      "/projects/apia/apia7-small.webp",
      "/projects/apia/apia8-small.webp",
      "/projects/apia/apia9-small.webp",
    ],
  },
  fooddelivery: {
    main: "/projects/foodDelivery/main.webp",
    mainSmall: "/projects/foodDelivery/main-small.webp",
    collage: "/projects/foodDelivery/foodDelivery9.webp",
    collageSmall: "/projects/foodDelivery/foodDelivery9-small.webp",
    logo: "/projects/foodDelivery/logo.webp",
    small: [
      "/projects/foodDelivery/foodDelivery1-small.webp",
      "/projects/foodDelivery/foodDelivery2-small.webp",
      "/projects/foodDelivery/foodDelivery3-small.webp",
      "/projects/foodDelivery/foodDelivery4-small.webp",
      "/projects/foodDelivery/foodDelivery5-small.webp",
      "/projects/foodDelivery/foodDelivery6-small.webp",
      "/projects/foodDelivery/foodDelivery7-small.webp",
      "/projects/foodDelivery/foodDelivery8-small.webp",
      "/projects/foodDelivery/foodDelivery9-small.webp",
    ],
    original: [
      "/projects/foodDelivery/foodDelivery1.webp",
      "/projects/foodDelivery/foodDelivery2.webp",
      "/projects/foodDelivery/foodDelivery3.webp",
      "/projects/foodDelivery/foodDelivery4.webp",
      "/projects/foodDelivery/foodDelivery5.webp",
      "/projects/foodDelivery/foodDelivery6.webp",
      "/projects/foodDelivery/foodDelivery7.webp",
      "/projects/foodDelivery/foodDelivery8.webp",
      "/projects/foodDelivery/foodDelivery9.webp",
    ],
  },
  jupiter: {
    main: "/projects/jupiter/jupiter1.webp", //TO DO
    mainSmall: "/projects/jupiter/jupiter1-small.webp", //TO DO
    collage: "/projects/jupiter/jupiter2.webp",
    collageSmall: "/projects/jupiter/jupiter2-small.webp",
    logo: "/projects/jupiter/logo.webp",
    small: [
      "/projects/jupiter/jupiter1-small.webp",
      "/projects/jupiter/jupiter2-small.webp",
      "/projects/jupiter/jupiter3-small.webp",
      "/projects/jupiter/jupiter4-small.webp",
      "/projects/jupiter/jupiter5-small.webp",
      "/projects/jupiter/jupiter6-small.webp",
    ],
    original: [
      "/projects/jupiter/jupiter1.webp",
      "/projects/jupiter/jupiter2.webp",
      "/projects/jupiter/jupiter3.webp",
      "/projects/jupiter/jupiter4.webp",
      "/projects/jupiter/jupiter5.webp",
      "/projects/jupiter/jupiter6.webp",
    ],
  },
  omegup: {
    main: "/projects/omegup/omegup1.webp", //TO DO
    mainSmall: "/projects/omegup/omegup1-small.webp", //TO DO
    collage: "/projects/omegup/omegup9.webp",
    collageSmall: "/projects/omegup/omegup9-small.webp",
    logo: "/projects/omegup/logo.webp",
    small: [
      "/projects/omegup/omegup1-small.webp",
      "/projects/omegup/omegup2-small.webp",
      "/projects/omegup/omegup3-small.webp",
      "/projects/omegup/omegup4-small.webp",
      "/projects/omegup/omegup5-small.webp",
      "/projects/omegup/omegup6-small.webp",
      "/projects/omegup/omegup7-small.webp",
      "/projects/omegup/omegup8-small.webp",
      "/projects/omegup/omegup9-small.webp",
    ],
    original: [
      "/projects/omegup/omegup1.webp",
      "/projects/omegup/omegup2.webp",
      "/projects/omegup/omegup3.webp",
      "/projects/omegup/omegup4.webp",
      "/projects/omegup/omegup5.webp",
      "/projects/omegup/omegup6.webp",
      "/projects/omegup/omegup7.webp",
      "/projects/omegup/omegup8.webp",
      "/projects/omegup/omegup9.webp",
    ],
  },
  school: {
    main: "/projects/school/school1.webp", // TODO
    mainSmall: "/projects/school/school1-small.webp", // TODO
    collage: "/projects/school/school2.webp",
    collageSmall: "/projects/school/school2-small.webp",
    logo: "/projects/school/logo.webp",
    small: [
      "/projects/school/school1-small.webp",
      "/projects/school/school2-small.webp",
      "/projects/school/school3-small.webp",
      "/projects/school/school4-small.webp",
      "/projects/school/school5-small.webp",
      "/projects/school/school6-small.webp",
      "/projects/school/school7-small.webp",
      "/projects/school/school8-small.webp",
      "/projects/school/school9-small.webp",
    ],
    original: [
      "/projects/school/school1.webp",
      "/projects/school/school2.webp",
      "/projects/school/school3.webp",
      "/projects/school/school4.webp",
      "/projects/school/school5.webp",
      "/projects/school/school6.webp",
      "/projects/school/school7.webp",
      "/projects/school/school8.webp",
      "/projects/school/school9.webp",
    ],
  },
  naqdiApp: {
    main: "/projects/naqdiApp/main.webp",
    mainSmall: "/projects/naqdiApp/main-small.webp",
    collage: "/projects/naqdiApp/naqdiApp2.webp",
    collageSmall: "/projects/naqdiApp/naqdiApp2-small.webp",
    logo: "/projects/naqdiApp/logo.webp",
    small: [
      "/projects/naqdiApp/naqdiApp1-small.webp",
      "/projects/naqdiApp/naqdiApp2-small.webp",
      "/projects/naqdiApp/naqdiApp3-small.webp",
      "/projects/naqdiApp/naqdiApp4-small.webp",
      "/projects/naqdiApp/naqdiApp5-small.webp",
      "/projects/naqdiApp/naqdiApp6-small.webp",
      "/projects/naqdiApp/naqdiApp7-small.webp",
      "/projects/naqdiApp/naqdiApp8-small.webp",
      "/projects/naqdiApp/naqdiApp9-small.webp",
    ],
    original: [
      "/projects/naqdiApp/naqdiApp1.webp",
      "/projects/naqdiApp/naqdiApp2.webp",
      "/projects/naqdiApp/naqdiApp3.webp",
      "/projects/naqdiApp/naqdiApp4.webp",
      "/projects/naqdiApp/naqdiApp5.webp",
      "/projects/naqdiApp/naqdiApp6.webp",
      "/projects/naqdiApp/naqdiApp7.webp",
      "/projects/naqdiApp/naqdiApp8.webp",
      "/projects/naqdiApp/naqdiApp9.webp",
    ],
  },
  taskManager: {
    main: "/projects/taskmanager/main.webp",
    mainSmall: "/projects/taskmanager/main-small.webp",
    collage: "/projects/taskmanager/taskmanager2.webp",
    collageSmall: "/projects/taskmanager/taskmanager2-small.webp",
    logo: "/projects/taskmanager/logo.webp",
    small: [
      "/projects/taskmanager/taskmanager1-small.webp",
      "/projects/taskmanager/taskmanager2-small.webp",
      "/projects/taskmanager/taskmanager3-small.webp",
      "/projects/taskmanager/taskmanager4-small.webp",
      "/projects/taskmanager/taskmanager5-small.webp",
      "/projects/taskmanager/taskmanager6-small.webp",
      "/projects/taskmanager/taskmanager7-small.webp",
    ],
    original: [
      "/projects/taskmanager/taskmanager1.webp",
      "/projects/taskmanager/taskmanager2.webp",
      "/projects/taskmanager/taskmanager3.webp",
      "/projects/taskmanager/taskmanager4.webp",
      "/projects/taskmanager/taskmanager5.webp",
      "/projects/taskmanager/taskmanager6.webp",
      "/projects/taskmanager/taskmanager7.webp",
    ],
  },
  bevioo: {
    main: "/projects/bevioo/main.webp",
    mainSmall: "/projects/bevioo/main-small.webp",
    collage: "/projects/bevioo/collage.webp",
    collageSmall: "/projects/bevioo/collage-small.webp",
    logo: "/projects/bevioo/logo.webp",
    small: [
      "/projects/bevioo/bevioo1-small.webp",
      "/projects/bevioo/bevioo2-small.webp",
      "/projects/bevioo/bevioo3-small.webp",
      "/projects/bevioo/bevioo4-small.webp",
      "/projects/bevioo/bevioo5-small.webp",
      "/projects/bevioo/bevioo6-small.webp",
      "/projects/bevioo/bevioo7-small.webp",
      "/projects/bevioo/bevioo8-small.webp",
      "/projects/bevioo/bevioo9-small.webp",
    ],
    original: [
      "/projects/bevioo/bevioo1.webp",
      "/projects/bevioo/bevioo2.webp",
      "/projects/bevioo/bevioo3.webp",
      "/projects/bevioo/bevioo4.webp",
      "/projects/bevioo/bevioo5.webp",
      "/projects/bevioo/bevioo6.webp",
      "/projects/bevioo/bevioo7.webp",
      "/projects/bevioo/bevioo8.webp",
      "/projects/bevioo/bevioo9.webp",
    ],
  },
  dsf: {
    main: "/projects/dsf/dsf1.webp", //TO DO
    mainSmall: "/projects/dsf/dsf1-small.webp", //TO DO
    collage: "/projects/dsf/dsf4.webp",
    collageSmall: "/projects/dsf/dsf4-small.webp",
    logo: "/projects/dsf/logo.webp",
    small: [
      "/projects/dsf/dsf1-small.webp",
      "/projects/dsf/dsf2-small.webp",
      "/projects/dsf/dsf3-small.webp",
      "/projects/dsf/dsf4-small.webp",
      "/projects/dsf/dsf5-small.webp",
      "/projects/dsf/dsf6-small.webp",
      "/projects/dsf/dsf7-small.webp",
      "/projects/dsf/dsf8-small.webp",
      "/projects/dsf/dsf9-small.webp",
    ],
    original: [
      "/projects/dsf/dsf1.webp",
      "/projects/dsf/dsf2.webp",
      "/projects/dsf/dsf3.webp",
      "/projects/dsf/dsf4.webp",
      "/projects/dsf/dsf5.webp",
      "/projects/dsf/dsf6.webp",
      "/projects/dsf/dsf7.webp",
      "/projects/dsf/dsf8.webp",
      "/projects/dsf/dsf9.webp",
    ],
  },
};
