export const projectImg1 = "/project1.jpg";
export const imgProfileSquare = "/imgProfileSquare.png";
export const skillsLogos: Record<SkillName, string> = {
  reactJs: "/skills/reactJs.png",
  nodeJs: "/skills/nodeJs.png",
  typeScript: "/skills/typescript.png",
  bootstrap: "/skills/bootstrap.png",
  materialUI: "/skills/materialUI.png",
  tailwindCss: "/skills/tailwind.png",
  primeFaces: "/skills/primereact.png",
  flutter: "/skills/flutter.png",
  sass: "/skills/sass.png",
  mongoDB: "/skills/mongodb.png",
  net: "/skills/dotnet.png",
  javaScript: "/skills/javaScript.png",
  sql: "/skills/sql.png",
  rxJs: "/skills/rxJs.png",
  git: "/skills/git.png",
  jira: "/skills/jira.png",
  redux: "/skills/redux.png",
  nextJs: "/skills/nextJs.png",
  meteor: "/skills/meteorJs.png",
};

export const projectImages: Record<
  ProjectNames,
  {
    original: string[];
    small: string[];
    main: string;
    collage: string;
    logo: string;
  }
> = {
  apia: {
    main: "/projects/apia/main.png",
    collage: "/projects/apia/collage.png",
    logo: "/projects/apia/logo.png",
    original: [
      "/projects/apia/apia1.png",
      "/projects/apia/apia2.png",
      "/projects/apia/apia3.png",
      "/projects/apia/apia4.png",
      "/projects/apia/apia5.png",
      "/projects/apia/apia6.png",
      "/projects/apia/apia7.png",
      "/projects/apia/apia8.png",
      "/projects/apia/apia9.png",
    ],
    small: [
      "/projects/apia/apia1-small.png",
      "/projects/apia/apia2-small.png",
      "/projects/apia/apia3-small.png",
      "/projects/apia/apia4-small.png",
      "/projects/apia/apia5-small.png",
      "/projects/apia/apia6-small.png",
      "/projects/apia/apia7-small.png",
      "/projects/apia/apia8-small.png",
      "/projects/apia/apia9-small.png",
    ],
  },
  fooddelivery: {
    main: "/projects/foodDelivery/main.png",
    collage: "/projects/foodDelivery/foodDelivery9.png",
    logo: "/projects/foodDelivery/logo.png",
    small: [
      "/projects/foodDelivery/foodDelivery1-small.png",
      "/projects/foodDelivery/foodDelivery2-small.png",
      "/projects/foodDelivery/foodDelivery3-small.png",
      "/projects/foodDelivery/foodDelivery4-small.png",
      "/projects/foodDelivery/foodDelivery5-small.png",
      "/projects/foodDelivery/foodDelivery6-small.png",
      "/projects/foodDelivery/foodDelivery7-small.png",
      "/projects/foodDelivery/foodDelivery8-small.png",
      "/projects/foodDelivery/foodDelivery9-small.png",
    ],
    original: [
      "/projects/foodDelivery/foodDelivery1.png",
      "/projects/foodDelivery/foodDelivery2.png",
      "/projects/foodDelivery/foodDelivery3.png",
      "/projects/foodDelivery/foodDelivery4.png",
      "/projects/foodDelivery/foodDelivery5.png",
      "/projects/foodDelivery/foodDelivery6.png",
      "/projects/foodDelivery/foodDelivery7.png",
      "/projects/foodDelivery/foodDelivery8.png",
      "/projects/foodDelivery/foodDelivery9.png",
    ],
  },
  jupiter: {
    main: "/projects/foodDelivery/jupiter1.png", //TO DO
    collage: "/projects/jupiter/jupiter2.png",
    logo: "/projects/jupiter/logo.png",
    small: [
      "/projects/jupiter/jupiter1-small.png",
      "/projects/jupiter/jupiter2-small.png",
      "/projects/jupiter/jupiter3-small.png",
      "/projects/jupiter/jupiter4-small.png",
      "/projects/jupiter/jupiter5-small.png",
      "/projects/jupiter/jupiter6-small.png",
    ],
    original: [
      "/projects/jupiter/jupiter1.png",
      "/projects/jupiter/jupiter2.png",
      "/projects/jupiter/jupiter3.png",
      "/projects/jupiter/jupiter4.png",
      "/projects/jupiter/jupiter5.png",
      "/projects/jupiter/jupiter6.png",
    ],
  },
  omegup: {
    main: "/projects/omegup/omegup1.png", //TO DO
    collage: "/projects/omegup/omegup9.png",
    logo: "/projects/omegup/logo.png",
    small: [
      "/projects/omegup/omegup1-small.png",
      "/projects/omegup/omegup2-small.png",
      "/projects/omegup/omegup3-small.png",
      "/projects/omegup/omegup4-small.png",
      "/projects/omegup/omegup5-small.png",
      "/projects/omegup/omegup6-small.png",
      "/projects/omegup/omegup7-small.png",
      "/projects/omegup/omegup8-small.png",
      "/projects/omegup/omegup9-small.png",
    ],
    original: [
      "/projects/omegup/omegup1.png",
      "/projects/omegup/omegup2.png",
      "/projects/omegup/omegup3.png",
      "/projects/omegup/omegup4.png",
      "/projects/omegup/omegup5.png",
      "/projects/omegup/omegup6.png",
      "/projects/omegup/omegup7.png",
      "/projects/omegup/omegup8.png",
      "/projects/omegup/omegup9.png",
    ],
  },
  school: {
    main: "/projects/school/school1.png",
    collage: "/projects/school/school2.png",
    logo: "/projects/school/logo.png",
    small: [
      "/projects/school/school1-small.png",
      "/projects/school/school2-small.png",
      "/projects/school/school3-small.png",
      "/projects/school/school4-small.png",
      "/projects/school/school5-small.png",
      "/projects/school/school6-small.png",
      "/projects/school/school7-small.png",
      "/projects/school/school8-small.png",
      "/projects/school/school9-small.png",
    ],
    original: [
      "/projects/school/school1.png",
      "/projects/school/school2.png",
      "/projects/school/school3.png",
      "/projects/school/school4.png",
      "/projects/school/school5.png",
      "/projects/school/school6.png",
      "/projects/school/school7.png",
      "/projects/school/school8.png",
      "/projects/school/school9.png",
    ],
  },
  naqdiApp: {
    main: "/projects/naqdiApp/main.png",
    collage: "/projects/naqdiApp/naqdiApp2.png",
    logo: "/projects/naqdiApp/logo.png",
    small: [
      "/projects/naqdiApp/naqdiApp1-small.png",
      "/projects/naqdiApp/naqdiApp2-small.png",
      "/projects/naqdiApp/naqdiApp3-small.png",
      "/projects/naqdiApp/naqdiApp4-small.png",
      "/projects/naqdiApp/naqdiApp5-small.png",
      "/projects/naqdiApp/naqdiApp6-small.png",
      "/projects/naqdiApp/naqdiApp7-small.png",
      "/projects/naqdiApp/naqdiApp8-small.png",
      "/projects/naqdiApp/naqdiApp9-small.png",
    ],
    original: [
      "/projects/naqdiApp/naqdiApp1.png",
      "/projects/naqdiApp/naqdiApp2.png",
      "/projects/naqdiApp/naqdiApp3.png",
      "/projects/naqdiApp/naqdiApp4.png",
      "/projects/naqdiApp/naqdiApp5.png",
      "/projects/naqdiApp/naqdiApp6.png",
      "/projects/naqdiApp/naqdiApp7.png",
      "/projects/naqdiApp/naqdiApp8.png",
      "/projects/naqdiApp/naqdiApp9.png",
    ],
  },
  taskManager: {
    main: "/projects/taskmanager/main.png",
    collage: "/projects/taskmanager/taskmanager2.jfif",
    logo: "/projects/taskmanager/logo.png",
    small: [
      "/projects/taskmanager/taskmanager1-small.jfif",
      "/projects/taskmanager/taskmanager2-small.jfif",
      "/projects/taskmanager/taskmanager3-small.jfif",
      "/projects/taskmanager/taskmanager4-small.jfif",
      "/projects/taskmanager/taskmanager5-small.jfif",
      "/projects/taskmanager/taskmanager6-small.jfif",
      "/projects/taskmanager/taskmanager7-small.jfif",
    ],
    original: [
      "/projects/taskmanager/taskmanager1.jfif",
      "/projects/taskmanager/taskmanager2.jfif",
      "/projects/taskmanager/taskmanager3.jfif",
      "/projects/taskmanager/taskmanager4.jfif",
      "/projects/taskmanager/taskmanager5.jfif",
      "/projects/taskmanager/taskmanager6.jfif",
      "/projects/taskmanager/taskmanager7.jfif",
    ],
  },
  bevioo: {
    main: "/projects/bevioo/main.png",
    collage: "/projects/bevioo/collage.png",
    logo: "/projects/bevioo/logo.png",
    small: [
      "/projects/bevioo/bevioo1-small.png",
      "/projects/bevioo/bevioo2-small.png",
      "/projects/bevioo/bevioo3-small.png",
      "/projects/bevioo/bevioo4-small.png",
      "/projects/bevioo/bevioo5-small.png",
      "/projects/bevioo/bevioo6-small.png",
      "/projects/bevioo/bevioo7-small.png",
      "/projects/bevioo/bevioo8-small.png",
      "/projects/bevioo/bevioo9-small.png",
    ],
    original: [
      "/projects/bevioo/bevioo1.png",
      "/projects/bevioo/bevioo2.png",
      "/projects/bevioo/bevioo3.png",
      "/projects/bevioo/bevioo4.png",
      "/projects/bevioo/bevioo5.png",
      "/projects/bevioo/bevioo6.png",
      "/projects/bevioo/bevioo7.png",
      "/projects/bevioo/bevioo8.png",
      "/projects/bevioo/bevioo9.png",
    ],
  },
  dsf: {
    main: "/projects/dsf/dsf1.png", //TO DO
    collage: "/projects/dsf/dsf4.png",
    logo: "/projects/dsf/logo.png",
    small: [
      "/projects/dsf/dsf1-small.png",
      "/projects/dsf/dsf2-small.png",
      "/projects/dsf/dsf3-small.png",
      "/projects/dsf/dsf4-small.png",
      "/projects/dsf/dsf5-small.png",
      "/projects/dsf/dsf6-small.png",
      "/projects/dsf/dsf7-small.png",
      "/projects/dsf/dsf8-small.png",
      "/projects/dsf/dsf9-small.png",
    ],
    original: [
      "/projects/dsf/dsf1.png",
      "/projects/dsf/dsf2.png",
      "/projects/dsf/dsf3.png",
      "/projects/dsf/dsf4.png",
      "/projects/dsf/dsf5.png",
      "/projects/dsf/dsf6.png",
      "/projects/dsf/dsf7.png",
      "/projects/dsf/dsf8.png",
      "/projects/dsf/dsf9.png",
    ],
  },
};

export const profileImg = "/profileImg.png";
