import { createUseStyles } from "react-jss";

export const useAboutStyle = createUseStyles((theme: AppTheme) => ({
  block: {
    alignItems: "center",
    aspectRatio: 2,
  },
  imageloadingContainer: {
    position: "absolute",
    zIndex: 2,
    inset: 0,
    insetInline: "0.7%",
    insetBlockStart: "-7.15%",
    height: "100%",
    overflow: "hidden",
    backgroundSize: "contain",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
  },
  image: {
    height: "100%",
    objectFit: "contain",
    objectPosition: "center",
  },
  hexagon: { width: "100%" },
  imgContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    color: theme.colorPrimary,
  },
  imgBgStart: {
    backgroundColor: theme.colorWhite,
    zIndex: 1,
    position: "absolute",
    width: "50%",
    insetBlock: 0,
    insetInlineEnd: "0%",
    animation: "$slideBg .5s .2s linear 1 forwards",
  },
  imgBgEnd: {
    zIndex: 1,
    backgroundColor: theme.colorWhite,
    position: "absolute",
    width: "50%",
    insetBlock: 0,
    insetInlineStart: "0%",
    animation: "$slideBg .5s .2s linear 1 forwards",
  },

  aboutColor: {
    color: theme.colorDark,
  },
  content: {
    display: "flex",
    flexDirection: "column",
    paddingBlockEnd: 10,
  },
  infoblock: {
    borderRadius: 20,
    paddingBlockEnd: 50,
    padding: 20,
    backgroundColor: theme.colorWhite,
  },
  infoCard: {
    animation: "$unblur .5s linear 1 forwards",
    filter: "blur(20px)",
    fontWeight: 600,
    paddingBlock: 15,
    paddingInline: 10,
    maxWidth: 250,
    borderRadius: 25,
    display: "flex",
    flexDirection: "column",
    textAlign: "center",
    gap: 5,
    width: "100%",
    backgroundColor: theme.colorLight,
    color: theme.colorWhite,
  },
  cardsContainer: {
    gap: 20,
    display: "flex",
    justifyContent: "center",
  },
  cardHeader: {
    display: "flex",
    gap: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  cardIcon: {
    width: 24,
    height: 24,
    color: theme.colorBlack,
  },
  cardLabel: { fontSize: 14, fontWeight: 400, color: theme.colorBlack },
  cardDescription: {
    fontSize: 22,
    fontWeight: 600,
    color: theme.colorPrimary,
  },
  description: {
    transform: "translateY(50px)",
    filter: "blur(20px)",
    opacity: 0,
    width: "80%",
    marginInline: "auto",
    paddingBlockStart: 20,
    paddingBlockEnd: 50,
    textAlign: "center",
    fontSize: 14,
    letterSpacing: 1,
    fontWeight: 500,
    animation: "$showContent .5s .2s linear 1 forwards",
  },
  resumeBtn: {
    cursor: "pointer",
    backgroundColor: theme.colorPrimary,
    borderRadius: 10,
    padding: 10,
    height: 44,
    fontSize: 16,
    fontWeight: 500,
    color: theme.colorWhite,
    boxShadow: `0px 2px 10px 2px ${theme.colorPrimary}`,
  },
  "@keyframes slideBg": {
    to: {
      width: "0%",
    },
  },
  "@keyframes unblur": {
    to: {
      filter: "blur(0px)",
    },
  },
  "@keyframes showContent": {
    to: {
      transform: "translateY(0px)",
      filter: "blur(0px)",
      opacity: 1,
    },
  },
}));
