import { projectImages, skillsLogos } from "../Constants/images";

export const SKILL_CARDS: Skill[] = [
  { id: "reactJs", logo: skillsLogos.reactJs, name: "ReactJs" },
  { id: "typeScript", logo: skillsLogos.typeScript, name: "TypeScript" },
  { id: "nextJs", logo: skillsLogos.nextJs, name: "NextJs" },
  { id: "nodeJs", logo: skillsLogos.nodeJs, name: "Node Js" },
  { id: "flutter", logo: skillsLogos.flutter, name: "Flutter" },
  { id: "net", logo: skillsLogos.net, name: ".Net" },
  { id: "materialUI", logo: skillsLogos.materialUI, name: "Material UI" },
  { id: "tailwindCss", logo: skillsLogos.tailwindCss, name: "Tailwind Css" },
  { id: "redux", logo: skillsLogos.redux, name: "redux" },
  { id: "bootstrap", logo: skillsLogos.bootstrap, name: "Bootstrap" },
  { id: "git", logo: skillsLogos.git, name: "Git" },
  { id: "primeFaces", logo: skillsLogos.primeFaces, name: "PrimeFaces" },
  { id: "meteor", logo: skillsLogos.meteor, name: "MeteorJs" },
  { id: "sass", logo: skillsLogos.sass, name: "Sass" },
  { id: "mongoDB", logo: skillsLogos.mongoDB, name: "MongoDB" },
  { id: "javaScript", logo: skillsLogos.javaScript, name: "JavaScript" },
  { id: "sql", logo: skillsLogos.sql, name: "SQL" },
  { id: "rxJs", logo: skillsLogos.rxJs, name: "RxJs" },
  { id: "jira", logo: skillsLogos.jira, name: "Jira" },
];

export const PROJECT_CARDS: Project[] = [
  {
    id: "school",
    title: "School",
    mainImage: projectImages.school.main,
    logo: projectImages.school.logo,
    description: [
      "An innovative organizational solution that enhances your school's administrative efficiency by delivering digital harmony, simplicity, fluidity, and excellence!",
      "A project that involves the design and implementation of a sophisticated ERP-CRM website meticulously crafted for seamless school management. Tailored user spaces for students, parents, and teachers provide an intuitive interface for a range of tasks. The platform boasts a rich feature set, including ERP tools for comprehensive resource planning, an intuitive scheduler, real-time web-push notifications, an efficient task manager, and an automated billing system. With a focus on optimizing and centralizing internal school services, this comprehensive solution enhances overall operational efficiency, offering a robust and user-friendly platform for effective school administration.",
    ],
    technologies: [
      "reactJs",
      "mongoDB",
      "javaScript",
      "typeScript",
      "redux",
      "nodeJs",
      "git",
    ],
    contributions: [
      "Designing user interfaces using ReactJs, Material-Ui.",
      "Implementing the business layers TypeScript.",
      "Implementing the back end using node.Js-Meteor.Js",
      "Building the DB structure using MongoDb.",
      "Contributing at designing the site base structure.",
    ],
  },
  {
    id: "naqdiApp",
    title: "Naqdi",
    mainImage: projectImages.naqdiApp.main,
    logo: projectImages.naqdiApp.logo,
    contributions: [
      "Created Naqdi Android/IOS mobile application using Flutter.",
      "Managed and contributed on Naqdi frontend web development process using React/typescript/Figma/Rest Api.",
      "Tested and optimized the project throughout the whole process.",
    ],
    description: [
      "An innovative application reshaping the way customers collect and redeem reward points from various merchants' loyalty reward programs (LRPs). ",
      "The app features three distinct portals:",
      "Merchant Portal: Empowering merchants to create and manage their LRPs seamlessly. Here, merchants can fine-tune their reward programs, monitor data, run targeted ads, and engage with app users through notifications or SMS services.",
      "Employee Portal: Catering to employees, this portal provides tools to reward customers with points, coupons, or stamps. It facilitates direct customer engagement, ensuring smooth reward distribution.",
      "Admin Portal: Serving as the central control hub, the admin portal oversees and manages all operations within Naqdi. From monitoring merchant activities to supervising employee interactions, this portal ensures efficient platform management.",
      "Naqdi transforms the landscape of loyalty reward programs, empowering merchants, employees, and administrators to efficiently manage, engage, and benefit from its innovative reward point withdrawal system.",
    ],

    technologies: [
      "reactJs",
      "materialUI",
      "typeScript",
      "redux",
      "javaScript",
      "mongoDB",
      "git",
    ],
  },
  {
    id: "bevioo",
    title: "Bevioo",
    mainImage: projectImages.bevioo.main,
    logo: projectImages.bevioo.logo,
    contributions: [
      "Took charge of overseeing and coordinating the development of the user interface and user experience to ensure the implementation of responsive and visually appealing designs.",
      "Managed the team by assigning tasks, setting clear expectations, and ensuring a comprehensive understanding of individual responsibilities. Actively reviewed tasks for quality assurance, emphasizing the simplification of processes and finding efficient solutions.",
      "I refactored the frontend API call services into a collection of straightforward and dynamic custom React hooks, aiming to simplify and expedite the project development phase.",
    ],

    description: [
      "Introducing Bevioo an advanced web ERP application designed to streamline internal operations across multiple companies.",
      " This comprehensive platform efficiently manages crucial aspects like client and supplier databases, product catalogs, order and delivery systems, billing, payments, and transaction tracking.",
      "With an array of specialized functionalities, Bevioo ensures precise stock management and manipulation, allowing for seamless tracking and control. Its diverse dashboards and comprehensive reports cater to various needs, offering insights into sales, purchases, treasury, and more.",
      "Bevioo simplifies complex workflows, providing a centralized solution that enhances efficiency and transparency across interconnected internal services within these companies.",
    ],

    technologies: [
      "reactJs",
      "materialUI",
      "typeScript",
      "net",
      "redux",
      "javaScript",
      "sql",
      "git",
    ],
  },
  {
    id: "dsf",
    title: "Delivery service France",
    mainImage: projectImages.dsf.original[0],
    logo: projectImages.dsf.logo,
    contributions: [
      "Created new user interfaces and adjusted the previous work to improve the compatibility with the Figma design to 100%. ",
    ],
    description: [
      "A cutting-edge platform for delivery service in France. This user-centric website offers an incredibly intuitive interface, delivering an exceptional experience for clients seeking hassle-free transportation or moving services.",
      "At its core, this platform simplifies the entire process. Users can effortlessly select their pickup and drop-off locations, while also specifying the shape and volume of their cargo—all through a seamless interface.",
      "This service redefines convenience. Clients no longer face the complexities of arranging transportation; instead, they engage with an interface designed for simplicity. Whether it's a few items or bulk cargo, this platform makes the entire process of transporting belongings a breeze.",
    ],

    technologies: [
      "nextJs",
      "materialUI",
      "typeScript",
      "nodeJs",
      "redux",
      "javaScript",
      "mongoDB",
      "jira",
      "git",
    ],
  },
  {
    id: "taskManager",
    title: "Task Manager",
    mainImage: projectImages.taskManager.main,
    logo: projectImages.taskManager.logo,
    description: [
      "Task Manager is a comprehensive and user-friendly application designed to streamline the management of large projects by facilitating the creation, assignment, and tracking of tasks among project members.",
      " This powerful tool enhances collaboration and ensures a smooth project progression through intuitive features and advanced functionalities.",
    ],

    technologies: [
      "typeScript",
      "reactJs",
      "materialUI",
      "redux",
      "git",
      "mongoDB",
      "jira",
      "nodeJs",
    ],

    contributions: [
      "Designing user interfaces using ReactJs, Material-Ui.",
      "Implementing the business layers TypeScript.",
      "Implementing the back end using node.Js-Meteor.",
      "Js Building the DB structure using MongoDb.",
      "Designing the site base structure",
    ],
  },
  {
    id: "omegup",
    title: "Omegup",
    mainImage: projectImages.omegup.original[0],
    logo: projectImages.omegup.logo,
    description: [
      "Omegup Site serves as the official online platform for Omegup, providing visitors with access to a diverse array of products developed by the company. This website not only showcases the innovative range of offerings but also highlights the various services provided by Omegup. In addition to presenting the product collection, the site offers comprehensive details about the company, giving visitors insights into its background, values, and mission.",
      " With a user-friendly interface, Omegup Site offers seamless navigation for individuals seeking information about the company and its offerings. The platform goes beyond product display by providing visitors with the opportunity to learn more about the company administration and easily reach out for inquiries or collaboration. Whether exploring the product catalog, learning about the company's services, or reaching out for communication, Omegup Site serves as a central hub for those interested in engaging with the company and its offerings.",
    ],

    technologies: [
      "reactJs",
      "typeScript",
      "materialUI",
      "jira",
      "javaScript",
      "nodeJs",
      "git",
    ],

    contributions: [
      "Designing user interfaces using React Js Material-Ui.",
      "Implementing the business layers TypeScript.",
      "Implementing the back end using node.Js-Meteor.Js",
    ],
  },
  {
    id: "fooddelivery",
    title: " Food delivery",
    mainImage: projectImages.fooddelivery.main,
    logo: projectImages.fooddelivery.logo,
    description: [
      "A comprehensive web application designed to revolutionize E-Commerce, focusing on sales across three main categories: Restaurants, Groceries, and an exclusive Food & Fruits section.",
      " This multifaceted platform accommodates diverse user roles, presenting tailored interfaces for admins, store or company owners, delivery personnel, and customers.",
      "One of the standout features is the integration of location-based services, allowing users to determine delivery locations through an intuitive map interface. Customers can seamlessly track their orders in real-time, from the moment of purchase through the delivery process. This real-time tracking capability ensures transparency and peace of mind, enhancing the overall user experience.",
      "Each section of the app is equipped with specialized systems: streamlined ordering processes, comprehensive delivery tracking functionalities, and efficient tools for managing customer-provider interactions. For instance, restaurant owners can manage their menus and orders, grocery stores can handle inventory and deliveries, while customers can explore, order, and track their purchases with ease.",
      "This sophisticated platform offers an interactive and dynamic space, fostering efficient interactions between customers and service providers. It's not just about buying; it's about creating an immersive experience that simplifies the entire process of shopping for food and groceries online, redefining convenience and reliability in E-Commerce.",
    ],

    technologies: [
      "reactJs",
      "typeScript",
      "primeFaces",
      "nodeJs",
      "mongoDB",
      "redux",
      "git",
      "jira",
    ],
    contributions: [
      "designing intuitive user interfaces using the dynamic capabilities of ReactJs and the feature-rich components of PrimeReact, enhancing the project with seamless functionality and polished design.",
      "Enriched the project by implementing robust business layers with TypeScript, ensuring strong typing and increased scalability while enhancing the codebase's reliability and maintainability.",
      "Contributed significantly by leveraging Node.js and Meteor.js to implement the backend, fostering a scalable and responsive infrastructure that powers the project's core functionality with efficiency and reliability.",
      "Constructed a tailored database structure in MongoDB, aligning precisely with client requirements and specifications. This facilitated a responsive and flexible data environment that adeptly addresses the project's unique needs.",
    ],
  },
  {
    description: [
      "The Agricultural Investment Promotion Agency (APIA) is embarking on a transformative initiative in collaboration with the Agriculture Ministry.",
      "Introducing an ERP-web application designed to meticulously manage internal services, projects, and entrepreneurs within its expansive incubator network. This innovative project places particular emphasis on efficiently overseeing diverse incubators affiliated with the agricultural promotion and investment agency. Each incubator is characterized by its unique location, comprehensive lists of adherent entrepreneurs, and a curated portfolio of programs aimed at fostering agricultural innovation. The ERP-web application facilitates seamless navigation through the intricate web of APIA's incubator ecosystem, providing a centralized platform to register and monitor entrepreneurs, their respective projects, and engagement in specialized programs. By implementing this comprehensive solution, APIA seeks to enhance collaboration, streamline project management, and empower entrepreneurs as they contribute to the growth and sustainability of the agricultural sector.",
    ],
    id: "apia",
    mainImage: projectImages.apia.main,
    logo: projectImages.apia.logo,
    technologies: [
      "reactJs",
      "typeScript",
      "primeFaces",
      "net",
      "redux",
      "javaScript",
      "sql",
      "jira",
      "nodeJs",
      "rxJs",
    ],
    title: "APIA",
    contributions: [
      "Designing user interfaces using ReactJs, PrimeReact.",
      "Implementing the business layers using Rx-js and TypeScript.",
      "Integrating Redux on the project to manage the global state of the the flow of data.",
      "Integrating some features on the back-end using C#",
    ],
  },
  {
    id: "jupiter",
    title: "Jupiter",
    mainImage: projectImages.jupiter.original[0],
    logo: projectImages.jupiter.logo,
    description: [
      "Jupiter, the robust web solution crafted exclusively for AZ Metal, a renowned French conglomerate overseeing multiple construction companies.",
      " This dynamic platform serves as the command center, seamlessly handling critical services like billing, supplier and client management, product catalogs, offers, and precise stock control.",
      " Tailored to unify operations, Jupiter offers a singular interface for diverse construction entities, revolutionizing coordination and efficiency across the board.",
    ],

    technologies: [
      "reactJs",
      "redux",
      "javaScript",
      "bootstrap",
      "git",
      "nodeJs",
    ],
    contributions: [
      "Designing user interfaces using ReactJs-Bootstrap",
      "Implementing the business layers",
      "Integrating Redux on the project",
    ],
  },
];
